[[roles]]
name = "admin"
# Define a list of routes with the syntax "Http-Method /path"
routes = ["GET /v1/openvpn/portforwarded", "GET /v1/openvpn/status", "GET /v1/openvpn/settings", "GET /v1/publicip/ip"]
# Define an authentication method with its parameters
auth = "basic"
username = "admin"
password = "admin"